// export default {
//   login: "john-smilga",
//   id: 42133389,
//   node_id: "MDQ6VXNlcjQyMTMzMzg5",
//   avatar_url: "https://avatars3.githubusercontent.com/u/42133389?v=4",
//   gravatar_id: "",
//   url: "https://api.github.com/users/john-smilga",
//   html_url: "https://github.com/john-smilga",
//   followers_url: "https://api.github.com/users/john-smilga/followers",
//   following_url:
//     "https://api.github.com/users/john-smilga/following{/other_user}",
//   gists_url: "https://api.github.com/users/john-smilga/gists{/gist_id}",
//   starred_url:
//     "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
//   subscriptions_url: "https://api.github.com/users/john-smilga/subscriptions",
//   organizations_url: "https://api.github.com/users/john-smilga/orgs",
//   repos_url: "https://api.github.com/users/john-smilga/repos",
//   events_url: "https://api.github.com/users/john-smilga/events{/privacy}",
//   received_events_url:
//     "https://api.github.com/users/john-smilga/received_events",
//   type: "User",
//   site_admin: false,
//   name: "John Smilga",
//   company: "Coding Addict",
//   blog: "www.johnsmilga.com",
//   location: "Los Angeles",
//   email: null,
//   hireable: null,
//   bio: "Creator of Coding Addict",
//   twitter_username: "john_smilga",
//   public_repos: 152,
//   public_gists: 0,
//   followers: 1495,
//   following: 0,
//   created_at: "2018-08-06T06:48:23Z",
//   updated_at: "2020-07-08T05:01:32Z",
// };

export default {
  login: "TatsuKenshi",
  id: 85489460,
  node_id: "MDQ6VXNlcjg1NDg5NDYw",
  avatar_url: "https://avatars.githubusercontent.com/u/85489460?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/TatsuKenshi",
  html_url: "https://github.com/TatsuKenshi",
  followers_url: "https://api.github.com/users/TatsuKenshi/followers",
  following_url:
    "https://api.github.com/users/TatsuKenshi/following{/other_user}",
  gists_url: "https://api.github.com/users/TatsuKenshi/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/TatsuKenshi/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/TatsuKenshi/subscriptions",
  organizations_url: "https://api.github.com/users/TatsuKenshi/orgs",
  repos_url: "https://api.github.com/users/TatsuKenshi/repos",
  events_url: "https://api.github.com/users/TatsuKenshi/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/TatsuKenshi/received_events",
  type: "User",
  site_admin: false,
  name: "Miroslav  Stankov",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 25,
  public_gists: 0,
  followers: 4,
  following: 0,
  created_at: "2021-06-07T10:14:36Z",
  updated_at: "2022-01-11T00:46:08Z",
};
